### ISSUE TITLE
3 Different errors

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#62] opened 2015-06-12 07:16 UTC
```
 File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 613, in get_prep_value
   return int(value)

ValueError: invalid literal for int() with base 10: 'D-0987_exp_2'


<WSGIRequest
path:/archives/items/D-0987_exp_2/dc/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'WG5fsYmofeCT0pnURB7cIlFz8e0RX1kF',
```
---------------
```
 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.1-py2.7.egg/telemeta/views/item.py", line 136, in item_detail
   title = ugettext('Item') + ' : ' + public_id + ' : ' + mess

TypeError: coercing to Unicode: need string or buffer, NoneType found


<WSGIRequest
path:/archives/markers/143394006304175431/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
```
--------------------
```
Traceback (most recent call last):

 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.1-py2.7.egg/telemeta/views/geo.py", line 45, in list_continents
   continents = MediaItem.objects.all().countries(group_by_continent=True)

 File "/usr/local/lib/python2.7/dist-packages/Telemeta-1.5.1-py2.7.egg/telemeta/models/query.py", line 134, in countries
   for continent in country.continents():

AttributeError: 'NoneType' object has no attribute 'continents'


<WSGIRequest
path:/geo/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'kFsp3fINjBUAqexG6ujdlTwV2GBgUdaU',
```

**Comment by AnasGhrab** [comment] 2015-06-15 09:53
I think that the first error comes because I have deleted the item directly from the mysql database... (I receive plenty of it...). Maybe I have also to delete a related entry in another table ?

**Comment by yomguy** [comment] 2015-06-15 15:47
That's really bad to make it in MySQL directly because django deals with a lot keys and links.
To make it by hand, prefer the django shell:
https://docs.djangoproject.com/en/1.8/intro/tutorial01/#playing-with-the-api

for ex:
```
./manage.py shell
>>> from telemeta.models import MediaItem
>>> item = MediaItem.objects.get(code='foobar')
>>> item.delete()
```

**Comment by yomguy** [comment] 2015-06-15 15:49
Please close the issue if the 3 errors are related with the SQL stuff (not sure for the 3rd)... ;)

**Comment by AnasGhrab** [comment] 2015-06-21 05:51
Finally, I think that the first error is not because of using the MySQL delete but because o the change of the code of the item. See https://github.com/Parisson/Telemeta/issues/64

**Comment by yomguy** [comment] 2015-06-22 14:16
I cannot reproduce the bug when changing a public_id of an item. 
What field did you changed exactly?

**Closed** 2015-09-16 19:28 UTC
